/** Allowlisted learn course IDs (must match frontend recordLessonXp course strings). */
const COURSE_IDS = [
  "oops-cpp",
  "pointers-cpp",
  "numpy-py",
  "pandas-py",
  "fastapi-py",
  "pytorch-py",
  "huggingface-py",
  "opencv-py",
  "python-fundamentals",
  "python-oop-py",
  "python-file-handling-py",
  "matplotlib-py",
  "ai-ml-py",
  "ml-py",
  "scipy-py",
  "cpp-fundamentals",
  "dsa-cpp",
  "cpp-data-structures",
  "functions-cpp",
  "modern-cpp",
  "stl-cpp",
  "c-fundamentals",
  "c-functions",
  "c-pointers",
  "c-data-structures",
  "c-memory-management",
  "c-file-handling",
  "c-projects",
  "js-fundamentals",
  "js-dom",
  "js-web-dev",
  "js-oops",
  "js-apis",
  "js-async",
  "js-es6-plus",
  "node-npm",
  "html-css-foundation",
  "css-animations",
  "css-layouts",
  "css-modern-features",
  "forms-semantic-html",
  "responsive-design",
  "sass-scss",
  "web-accessibility",
  "php-fundamentals",
  "php-forms",
  "php-mysql",
  "php-oop",
  "php-projects",
  "php-sessions",
  "laravel-basics",
  "ruby-fundamentals",
  "ruby-gems",
  "ruby-blocks-modules",
  "ruby-file-handling",
  "ruby-oop",
  "ruby-on-rails",
  "csharp-fundamentals",
  "csharp-aspnet-basics",
  "csharp-collections",
  "csharp-file-handling",
  "csharp-linq",
  "csharp-oop",
  "csharp-projects",
  "sql-fundamentals",
  "sql-queries",
  "sql-joins",
  "sql-subqueries",
  "sql-aggregate-functions",
  "sql-views",
  "sql-indexes",
  "sql-stored-procedures",
  "sql-projects",
  "go-fundamentals",
  "go-apis",
  "go-concurrency",
  "go-functions",
  "go-modules",
  "go-web-development",
  "rust-fundamentals",
  "rust-collections",
  "rust-concurrency",
  "rust-memory",
  "rust-projects",
  "java-fundamentals",
  "java-intermediate",
  "java-advanced",
  "java-collections",
  "java-exception",
  "java-multithreading",
  "java-jdbc",
  "java-spring-boot",
  "java-projects",
  "powershell-fundamentals",
  "powershell-scripting",
  "powershell-administration",
  "powershell-projects",
  "batchfile-fundamentals",
  "batchfile-automation",
  "batchfile-projects",
  "windows-scripting",
  "quantum-computing-fundamentals",
  "quantum-mechanics-for-programmers",
  "quantum-algorithms",
  "quantum-multi-syntax",
  "quantum-paradigm-coding",
  "quantum-programming-projects",
  "qsharp-fundamentals",
  "qsharp-quantum-programming-basics",
  "qsharp-quantum-gates",
  "qsharp-quantum-algorithms",
  "qsharp-quantum-projects",
  "software-engineering-fundamentals",
];

const COURSE_ID_SET = new Set(COURSE_IDS);

function isValidCourseId(courseId) {
  return COURSE_ID_SET.has(String(courseId || "").trim());
}

function assertCourseId(courseId) {
  const id = String(courseId || "").trim();
  if (!isValidCourseId(id)) {
    const err = new Error(`Unknown courseId: ${courseId}`);
    err.statusCode = 400;
    throw err;
  }
  return id;
}

module.exports = {
  COURSE_IDS,
  COURSE_ID_SET,
  isValidCourseId,
  assertCourseId,
};
